type: service
body: |
  name: second-service
  lb: true
  path: /home/d0sta/ppass/config_files/python/second_service.py
  technology: python
  lbconfig:
    upstreamname: second_service
    listenport: 8081
    domain: second.local
